apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumervnext-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumervnext
  template:
    metadata:
      labels:
        app: consumervnext
    spec:
      containers:
      - name: consumervnext
        image: perocha.azurecr.io/consumervnext:latest
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: appinsights
              key: instrumentationkey
        - name: EVENTHUB_CONSUMERVNEXT_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: eventhubconsumervnext
              key: eventhubconsumervnextconnectionstring
        - name: CHECKPOINTSTORE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: checkpointstore
              key: checkpointstoreconnectionstring
        - name: APPCONFIGURATION_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: appconfiguration
              key: appconfigurationconnectionstring