apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: perocha.azurecr.io/consumer:latest
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: appinsights
              key: instrumentationkey
        - name: EVENTHUB_CONSUMER_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: eventhubconsumer
              key: eventhubconsumerconnectionstring
        - name: STORAGE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: storage
              key: storageaccountname
        - name: STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: storageconnection
              key: storageconnectionstring
        - name: PARTITION_LEASE_CONTAINER
          valueFrom:
            secretKeyRef:
              name: partitionlease
              key: partitionleasecontainer
