apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumervnext-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumervnext
  template:
    metadata:
      labels:
        app: consumervnext
    spec:
      containers:
      - name: consumervnext
        image: perocha.azurecr.io/consumervnext:latest
        restartPolicy: Never
        env:
        - name: APPCONFIGURATION_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: appconfiguration
              key: appconfigurationconnectionstring