name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{secrets.ACR_NAMESPACE}}.azurecr.io
        username: ${{secrets.ACR_USERNAME}}
        password: ${{secrets.ACR_PASSWORD}}

    - name: Build consumer image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./consumer/Dockerfile
        push: true
        tags: ${{secrets.ACR_NAMESPACE}}.azurecr.io/consumer:latest

    - name: Build publisher image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./publisher/Dockerfile
        push: true
        tags: ${{secrets.ACR_NAMESPACE}}.azurecr.io/publisher:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER }}

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          k8s/publisher-deployment.yaml
          k8s/publisher-service.yaml
