name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{secrets.ACR_NAMESPACE}}.azurecr.io
        username: ${{secrets.ACR_USERNAME}}
        password: ${{secrets.ACR_PASSWORD}}

    - name: Build consumer image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./consumer/Dockerfile
        push: true
        tags: ${{secrets.ACR_NAMESPACE}}.azurecr.io/consumer:latest

    - name: Build publisher image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./publisher/Dockerfile
        push: true
        tags: ${{secrets.ACR_NAMESPACE}}.azurecr.io/publisher:latest
