name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build consumer image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./consumer/Dockerfile
        push: false

    - name: Build publisher image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./publisher/Dockerfile
        push: false
